version: 2

sphinx:
  configuration: docs/conf.py

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    pre_build:
      - mkdir docs/_build

python:
  install:
    - requirements: docs/requirements.txt
